CREATE TABLE FIVE_INFO(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(5000) NOT NULL,
	WDATE DATE NOT NULL
);

FIVE_INFO_PK(SEQ)
FK_FIVE_INFO_ID(ID)