DROP TABLE FIVE_QNA
CASCADE CONSTRAINTS

CREATE TABLE FIVE_QNA(
	SEQ NUMBER(8) PRIMARY KEY,
	TITLE VARCHAR2(400) NOT NULL,
	CONTENTS VARCHAR2(4000) NOT NULL,
	PART_SEQ NUMBER(8),
	ID VARCHAR2(50),
	SECRET NUMBER(1),
	WDATE VARCHAR2(50) NOT NULL,
	UDATE VARCHAR2(50) NOT NULL
)

ALTER TABLE FIVE_QNA
ADD
CATEGORY_SEQ NUMBER(10)

CREATE SEQUENCE FIVE_QNA_SEQ
START WITH 1
INCREMENT BY 1

ALTER TABLE FIVE_QNA
ADD
CONSTRAINT FK_QNA_ID FOREIGN KEY(ID)
REFERENCES FIVE_MEMBER(ID)

ALTER TABLE FIVE_QNA
ADD
CONSTRAINT FK_QNA_PARTSEQ FOREIGN KEY(PART_SEQ)
REFERENCES FIVE_PART(SEQ)

ALTER TABLE FIVE_QNA
ADD
CONSTRAINT FK_QNA_CATESEQ FOREIGN KEY(CATEGORY_SEQ)
REFERENCES FIVE_CATEGORY(SEQ)

SELECT SEQ, TITLE, CONTENTS, PART_SEQ, ID, SECRET, WDATE
FROM
(
SELECT ROW_NUMBER()OVER(ORDER BY WDATE DESC) AS RNUM,
	SEQ, TITLE, CONTENTS, PART_SEQ, ID, SECRET, WDATE
FROM FIVE_QNA
ORDER BY WDATE DESC
)
WHERE ? <= RNUM AND RNUM <= ?


 SELECT SEQ, TITLE, CONTENTS, PART_SEQ, ID, SECRET, WDATE  
 FROM  ( 
 SELECT ROW_NUMBER()OVER(ORDER BY WDATE DESC) AS RNUM, 
 SEQ, TITLE, CONTENTS, PART_SEQ, ID, SECRET, WDATE  
 FROM FIVE_QNA  
 WHERE PART_SEQ = 1
 ORDER BY WDATE DESC  )  
 WHERE 1 <= RNUM AND RNUM <= 10  
 
 select *
from FIVE_member
 where id='a'

 
 SELECT SEQ, ID, TITLE, UDATE  
 FROM  
 ( SELECT ROW_NUMBER()OVER(ORDER BY WDATE DESC) AS RNUM, 
	SEQ, ID, TITLE, UDATE  
 FROM FIVE_QNA  
 WHERE TITLE LIKE '%5%'
 ORDER BY SEQ DESC
 )
 WHERE 1<= RNUM AND RNUM <=10 
 AND TITLE='%5%'
  ORDER BY SEQ DESC   
 
 
 
