
select *
from five_category
where seq = 56

SELECT SEQ, P_NAME, P_CATEGORY, FILENAME  
FROM  
( SELECT ROW_NUMBER()OVER(ORDER BY WDATE DESC) AS RNUM, 	
SEQ, P_NAME, P_CATEGORY, FILENAME   
FROM FIVE_CATEGORY  
 ORDER BY SEQ DESC  )  
 
 SELECT *
 FROM USER_SEQUENCES
 
 INSERT INTO FIVE_CATEGORY VALUES(SEQ_PRODUCT.NEXTVAL,'TEST','삭제하지말아주세요','면','KOREA',2500,'top',0,1,'top06.jpg')
 INSERT INTO FIVE_CATEGORY VALUES(SEQ_PRODUCT.NEXTVAL,'TEST2','삭제하지말아주세요','면','KOREA',2500,'top',0,1,'top06.jpg')
 INSERT INTO FIVE_CATEGORY VALUES(SEQ_PRODUCT.NEXTVAL,'TEST3','삭제하지말아주세요','면','KOREA',2500,'top',0,1,'top06.jpg')
 INSERT INTO FIVE_CATEGORY VALUES(SEQ_PRODUCT.NEXTVAL,'TEST4','삭제하지말아주세요','면','KOREA',2500,'top',0,1,'top06.jpg')
 INSERT INTO FIVE_CATEGORY VALUES(SEQ_PRODUCT.NEXTVAL,'TEST5','삭제하지말아주세요','면','KOREA',2500,'top',0,1,'top06.jpg')
 INSERT INTO FIVE_CATEGORY VALUES(SEQ_PRODUCT.NEXTVAL,'TEST6','삭제하지말아주세요','면','KOREA',2500,'top',0,1,'top06.jpg')

 SELECT *
 FROM FIVE_SUGGEST A
 JOIN FIVE_SUGGEST_COMMENT B ON A.REF = B.SUGGEST_NO
 
 SELECT *
 FROM FIVE_SUGGEST_COMMENT
 
 select *
 from tab
 
 select *
 from five_member

 
 