SELECT * FROM FIVE_ORDER


SELECT c.SEQ, c.ID, c.ITEM_SEQ, c.QTY, c.COLOR, c.ITEM_SIZE, g.P_NAME , g.P_PRICE, g.FILENAME 
FROM FIVE_CART c , FIVE_CATEGORY g 
WHERE c.ITEM_SEQ = g.SEQ AND ID = 'a'
ORDER BY SEQ DESC

SELECT o.SEQ, o.ID, o.ITEM_SEQ, o.QTY, o.COLOR, o.ITEM_SIZE, g.P_NAME , g.P_PRICE, g.FILENAME 
FROM FIVE_ORDER o , FIVE_CATEGORY g 
WHERE o.ITEM_SEQ = g.SEQ AND o.ID = 'a'
ORDER BY SEQ DESC 

SELECT SEQ, P_NAME, P_INFO ,P_MATERIAL, P_MADEIN, P_PRICE, P_CATEGORY, P_READCOUNT, P_KIND, FILENAME 
FROM (SELECT ROW_NUMBER()OVER(ORDER BY P_READCOUNT DESC) AS RNUM, SEQ, P_NAME, P_INFO ,P_MATERIAL, P_MADEIN, P_PRICE, P_CATEGORY, P_READCOUNT, P_KIND, FILENAME 
 FROM FIVE_CATEGORY ) 
WHERE  RNUM >=1 AND RNUM <=8