SELECT * FROM FIVE_CART


SELECT c.SEQ, c.ID, c.ITEM_SEQ, c.QTY, c.COLOR, c.ITEM_SIZE, g.P_NAME , g.P_PRICE, g.FILENAME 
FROM FIVE_CART c , FIVE_CATEGORY g 
WHERE c.ITEM_SEQ = g.SEQ AND ID = 'a'
ORDER BY SEQ DESC