CREATE TABLE FIVE_REPLY(
	SEQ NUMBER(8) PRIMARY KEY,
	QNA_SEQ NUMBER(8),
	CATEGORY_SEQ NUMBER(8),
	ID	VARCHAR2(50) NOT NULL,
	WDATE VARCHAR2(50) NOT NULL,
	UDATE VARCHAR2(50) NOT NULL,
	SECRET NUMBER(1)
)

CREATE SEQUENCE FIVE_REPLY_SEQ
START WITH 1
INCREMENT BY 1

ALTER TABLE FIVE_REPLY
ADD
CONSTRAINT FK_REPLY_ID FOREIGN KEY(ID)
REFERENCES FIVE_MEMBER(ID)

ALTER TABLE FIVE_REPLY
ADD
CONSTRAINT FK_REPLY_QNASEQ FOREIGN KEY(QNA_SEQ)
REFERENCES FIVE_QNA(SEQ)

ALTER TABLE FIVE_REPLY
ADD
CONSTRAINT FK_REPLY_CATESEQ FOREIGN KEY(CATEGORY_SEQ)
REFERENCES FIVE_CATEGORY(SEQ)

ALTER TABLE FIVE_REPLY
ADD
CONTENTS VARCHAR2(4000)

select *
from five_qna
where seq in (82,83)

select COUNT(*)
from five_reply
WHERE QNA_SEQ = 18

in (82,83)


